name: publish
on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: publish standalone project
        run: |
          dotnet publish -c Release -o build/release src/MonBand.Windows.Standalone

      - name: publish comhost project
        run: |
          dotnet publish -c Release -o build/release src/MonBand.Windows.ComHost

      - name: build release archive
        run: |
          $Dll = Get-Item("./build/release/MonBand.Core.dll")
          $MONBAND_VER = $Dll.VersionInfo.ProductVersion
          7z a -t7z -mx=9 MonBand-$MONBAND_VER.7z ./build/release/*
          
      - uses: ncipollo/release-action@v1
        with:
            artifacts: "MonBand-*.7z"
            generateReleaseNotes: true
            allowUpdates: true
            token: ${{ secrets.GITHUB_TOKEN }}
